# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# TODO enable pylint
#- name: Linting with Pylint
#  uses: fylein/python-pylint-github-action@v1
#  with:
#    args: aoc_2015 aoc_2018

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    
    - name: Install dependencies
      run: |
        pipenv install --dev
    
    - name:  Type checking with Mypy
      uses: jpetrucciani/mypy-check@master
      with:
        path: 'aoc_2015 aoc_2018'

    - name: Test with pytest
      run: |
        pipenv run pytest aoc_2015 aoc_2018 
